# Generated by Django 2.0.2 on 2018-02-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_article_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_image',
            new_name='image',
        ),
    ]
