# Generated by Django 2.0.2 on 2018-02-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180215_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='article_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_title',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
