# Generated by Django 2.0.2 on 2018-02-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180215_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_text',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
