# Generated by Django 2.0.2 on 2018-03-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180301_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='count_comments',
            field=models.IntegerField(default=0, verbose_name='Count comments'),
        ),
    ]
