# Generated by Django 2.0.2 on 2018-03-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180301_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='count_comments',
        ),
    ]
