# Generated by Django 2.0.2 on 2018-03-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180301_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count_comments',
            field=models.BigIntegerField(default=0, verbose_name='Count comments'),
        ),
    ]
