# Generated by Django 2.0.2 on 2018-03-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180302_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
