# Generated by Django 2.0.2 on 2018-03-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180303_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='count_comments',
        ),
        migrations.RemoveField(
            model_name='article',
            name='count_likes',
        ),
    ]
